# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='orgUni',
        ),
    ]
